/* Generated by zwangine build tools - do NOT edit this file! */
package org.zenithblox.component.file;

import org.zenithblox.ZwangineContext;
import org.zenithblox.spi.GeneratedPropertyConfigurer;
import org.zenithblox.spi.PropertyConfigurerGetter;
import org.zenithblox.support.component.PropertyConfigurerSupport;

import javax.annotation.processing.Generated;
import java.util.Map;

/**
 * Generated by zwangine build tools - do NOT edit this file!
 */
@Generated("org.zenithblox.maven.packaging.EndpointSchemaGeneratorMojo")
@SuppressWarnings("unchecked")
public class FileEndpointConfigurer extends PropertyConfigurerSupport implements GeneratedPropertyConfigurer, PropertyConfigurerGetter {

    @Override
    public boolean configure(ZwangineContext zwangineContext, Object obj, String name, Object value, boolean ignoreCase) {
        FileEndpoint target = (FileEndpoint) obj;
        switch (ignoreCase ? name.toLowerCase() : name) {
        case "allownullbody":
        case "allowNullBody": target.setAllowNullBody(property(zwangineContext, boolean.class, value)); return true;
        case "antexclude":
        case "antExclude": target.setAntExclude(property(zwangineContext, String.class, value)); return true;
        case "antfiltercasesensitive":
        case "antFilterCaseSensitive": target.setAntFilterCaseSensitive(property(zwangineContext, boolean.class, value)); return true;
        case "antinclude":
        case "antInclude": target.setAntInclude(property(zwangineContext, String.class, value)); return true;
        case "appendchars":
        case "appendChars": target.setAppendChars(property(zwangineContext, String.class, value)); return true;
        case "autocreate":
        case "autoCreate": target.setAutoCreate(property(zwangineContext, boolean.class, value)); return true;
        case "autocreatestepwise":
        case "autoCreateStepwise": target.setAutoCreateStepwise(property(zwangineContext, boolean.class, value)); return true;
        case "backofferrorthreshold":
        case "backoffErrorThreshold": target.setBackoffErrorThreshold(property(zwangineContext, int.class, value)); return true;
        case "backoffidlethreshold":
        case "backoffIdleThreshold": target.setBackoffIdleThreshold(property(zwangineContext, int.class, value)); return true;
        case "backoffmultiplier":
        case "backoffMultiplier": target.setBackoffMultiplier(property(zwangineContext, int.class, value)); return true;
        case "bridgeerrorhandler":
        case "bridgeErrorHandler": target.setBridgeErrorHandler(property(zwangineContext, boolean.class, value)); return true;
        case "browselimit":
        case "browseLimit": target.setBrowseLimit(property(zwangineContext, int.class, value)); return true;
        case "buffersize":
        case "bufferSize": target.setBufferSize(property(zwangineContext, int.class, value)); return true;
        case "charset": target.setCharset(property(zwangineContext, String.class, value)); return true;
        case "checksumfilealgorithm":
        case "checksumFileAlgorithm": target.setChecksumFileAlgorithm(property(zwangineContext, String.class, value)); return true;
        case "chmod": target.setChmod(property(zwangineContext, String.class, value)); return true;
        case "chmoddirectory":
        case "chmodDirectory": target.setChmodDirectory(property(zwangineContext, String.class, value)); return true;
        case "copyanddeleteonrenamefail":
        case "copyAndDeleteOnRenameFail": target.setCopyAndDeleteOnRenameFail(property(zwangineContext, boolean.class, value)); return true;
        case "delay": target.setDelay(property(zwangineContext, long.class, value)); return true;
        case "delete": target.setDelete(property(zwangineContext, boolean.class, value)); return true;
        case "directorymustexist":
        case "directoryMustExist": target.setDirectoryMustExist(property(zwangineContext, boolean.class, value)); return true;
        case "donefilename":
        case "doneFileName": target.setDoneFileName(property(zwangineContext, String.class, value)); return true;
        case "eagerdeletetargetfile":
        case "eagerDeleteTargetFile": target.setEagerDeleteTargetFile(property(zwangineContext, boolean.class, value)); return true;
        case "eagermaxmessagesperpoll":
        case "eagerMaxMessagesPerPoll": target.setEagerMaxMessagesPerPoll(property(zwangineContext, boolean.class, value)); return true;
        case "exceptionhandler":
        case "exceptionHandler": target.setExceptionHandler(property(zwangineContext, org.zenithblox.spi.ExceptionHandler.class, value)); return true;
        case "exchangepattern":
        case "exchangePattern": target.setExchangePattern(property(zwangineContext, org.zenithblox.ExchangePattern.class, value)); return true;
        case "exclude": target.setExclude(property(zwangineContext, String.class, value)); return true;
        case "excludeext":
        case "excludeExt": target.setExcludeExt(property(zwangineContext, String.class, value)); return true;
        case "exclusivereadlockstrategy":
        case "exclusiveReadLockStrategy": target.setExclusiveReadLockStrategy(property(zwangineContext, org.zenithblox.component.file.GenericFileExclusiveReadLockStrategy.class, value)); return true;
        case "extendedattributes":
        case "extendedAttributes": target.setExtendedAttributes(property(zwangineContext, String.class, value)); return true;
        case "fileexist":
        case "fileExist": target.setFileExist(property(zwangineContext, org.zenithblox.component.file.GenericFileExist.class, value)); return true;
        case "filename":
        case "fileName": target.setFileName(property(zwangineContext, String.class, value)); return true;
        case "filter": target.setFilter(property(zwangineContext, org.zenithblox.component.file.GenericFileFilter.class, value)); return true;
        case "filterdirectory":
        case "filterDirectory": target.setFilterDirectory(property(zwangineContext, String.class, value)); return true;
        case "filterfile":
        case "filterFile": target.setFilterFile(property(zwangineContext, String.class, value)); return true;
        case "flatten": target.setFlatten(property(zwangineContext, boolean.class, value)); return true;
        case "forcewrites":
        case "forceWrites": target.setForceWrites(property(zwangineContext, boolean.class, value)); return true;
        case "greedy": target.setGreedy(property(zwangineContext, boolean.class, value)); return true;
        case "idempotent": target.setIdempotent(property(zwangineContext, Boolean.class, value)); return true;
        case "idempotenteager":
        case "idempotentEager": target.setIdempotentEager(property(zwangineContext, Boolean.class, value)); return true;
        case "idempotentkey":
        case "idempotentKey": target.setIdempotentKey(property(zwangineContext, String.class, value)); return true;
        case "idempotentrepository":
        case "idempotentRepository": target.setIdempotentRepository(property(zwangineContext, org.zenithblox.spi.IdempotentRepository.class, value)); return true;
        case "inprogressrepository":
        case "inProgressRepository": target.setInProgressRepository(property(zwangineContext, org.zenithblox.spi.IdempotentRepository.class, value)); return true;
        case "include": target.setInclude(property(zwangineContext, String.class, value)); return true;
        case "includeext":
        case "includeExt": target.setIncludeExt(property(zwangineContext, String.class, value)); return true;
        case "includehiddendirs":
        case "includeHiddenDirs": target.setIncludeHiddenDirs(property(zwangineContext, boolean.class, value)); return true;
        case "includehiddenfiles":
        case "includeHiddenFiles": target.setIncludeHiddenFiles(property(zwangineContext, boolean.class, value)); return true;
        case "initialdelay":
        case "initialDelay": target.setInitialDelay(property(zwangineContext, long.class, value)); return true;
        case "jailstartingdirectory":
        case "jailStartingDirectory": target.setJailStartingDirectory(property(zwangineContext, boolean.class, value)); return true;
        case "keeplastmodified":
        case "keepLastModified": target.setKeepLastModified(property(zwangineContext, boolean.class, value)); return true;
        case "lazystartproducer":
        case "lazyStartProducer": target.setLazyStartProducer(property(zwangineContext, boolean.class, value)); return true;
        case "localworkdirectory":
        case "localWorkDirectory": target.setLocalWorkDirectory(property(zwangineContext, String.class, value)); return true;
        case "maxdepth":
        case "maxDepth": target.setMaxDepth(property(zwangineContext, int.class, value)); return true;
        case "maxmessagesperpoll":
        case "maxMessagesPerPoll": target.setMaxMessagesPerPoll(property(zwangineContext, int.class, value)); return true;
        case "mindepth":
        case "minDepth": target.setMinDepth(property(zwangineContext, int.class, value)); return true;
        case "move": target.setMove(property(zwangineContext, String.class, value)); return true;
        case "moveexisting":
        case "moveExisting": target.setMoveExisting(property(zwangineContext, String.class, value)); return true;
        case "moveexistingfilestrategy":
        case "moveExistingFileStrategy": target.setMoveExistingFileStrategy(property(zwangineContext, org.zenithblox.component.file.strategy.FileMoveExistingStrategy.class, value)); return true;
        case "movefailed":
        case "moveFailed": target.setMoveFailed(property(zwangineContext, String.class, value)); return true;
        case "noop": target.setNoop(property(zwangineContext, boolean.class, value)); return true;
        case "oncompletionexceptionhandler":
        case "onCompletionExceptionHandler": target.setOnCompletionExceptionHandler(property(zwangineContext, org.zenithblox.spi.ExceptionHandler.class, value)); return true;
        case "pollstrategy":
        case "pollStrategy": target.setPollStrategy(property(zwangineContext, org.zenithblox.spi.PollingConsumerPollStrategy.class, value)); return true;
        case "premove":
        case "preMove": target.setPreMove(property(zwangineContext, String.class, value)); return true;
        case "presort":
        case "preSort": target.setPreSort(property(zwangineContext, boolean.class, value)); return true;
        case "probecontenttype":
        case "probeContentType": target.setProbeContentType(property(zwangineContext, boolean.class, value)); return true;
        case "processstrategy":
        case "processStrategy": target.setProcessStrategy(property(zwangineContext, org.zenithblox.component.file.GenericFileProcessStrategy.class, value)); return true;
        case "readlock":
        case "readLock": target.setReadLock(property(zwangineContext, String.class, value)); return true;
        case "readlockcheckinterval":
        case "readLockCheckInterval": target.setReadLockCheckInterval(property(zwangineContext, long.class, value)); return true;
        case "readlockdeleteorphanlockfiles":
        case "readLockDeleteOrphanLockFiles": target.setReadLockDeleteOrphanLockFiles(property(zwangineContext, boolean.class, value)); return true;
        case "readlockidempotentreleaseasync":
        case "readLockIdempotentReleaseAsync": target.setReadLockIdempotentReleaseAsync(property(zwangineContext, boolean.class, value)); return true;
        case "readlockidempotentreleaseasyncpoolsize":
        case "readLockIdempotentReleaseAsyncPoolSize": target.setReadLockIdempotentReleaseAsyncPoolSize(property(zwangineContext, int.class, value)); return true;
        case "readlockidempotentreleasedelay":
        case "readLockIdempotentReleaseDelay": target.setReadLockIdempotentReleaseDelay(property(zwangineContext, int.class, value)); return true;
        case "readlockidempotentreleaseexecutorservice":
        case "readLockIdempotentReleaseExecutorService": target.setReadLockIdempotentReleaseExecutorService(property(zwangineContext, java.util.concurrent.ScheduledExecutorService.class, value)); return true;
        case "readlocklogginglevel":
        case "readLockLoggingLevel": target.setReadLockLoggingLevel(property(zwangineContext, org.zenithblox.LoggingLevel.class, value)); return true;
        case "readlockmarkerfile":
        case "readLockMarkerFile": target.setReadLockMarkerFile(property(zwangineContext, boolean.class, value)); return true;
        case "readlockminage":
        case "readLockMinAge": target.setReadLockMinAge(property(zwangineContext, long.class, value)); return true;
        case "readlockminlength":
        case "readLockMinLength": target.setReadLockMinLength(property(zwangineContext, long.class, value)); return true;
        case "readlockremoveoncommit":
        case "readLockRemoveOnCommit": target.setReadLockRemoveOnCommit(property(zwangineContext, boolean.class, value)); return true;
        case "readlockremoveonrollback":
        case "readLockRemoveOnRollback": target.setReadLockRemoveOnRollback(property(zwangineContext, boolean.class, value)); return true;
        case "readlocktimeout":
        case "readLockTimeout": target.setReadLockTimeout(property(zwangineContext, long.class, value)); return true;
        case "recursive": target.setRecursive(property(zwangineContext, boolean.class, value)); return true;
        case "renameusingcopy":
        case "renameUsingCopy": target.setRenameUsingCopy(property(zwangineContext, boolean.class, value)); return true;
        case "repeatcount":
        case "repeatCount": target.setRepeatCount(property(zwangineContext, long.class, value)); return true;
        case "runlogginglevel":
        case "runLoggingLevel": target.setRunLoggingLevel(property(zwangineContext, org.zenithblox.LoggingLevel.class, value)); return true;
        case "scheduledexecutorservice":
        case "scheduledExecutorService": target.setScheduledExecutorService(property(zwangineContext, java.util.concurrent.ScheduledExecutorService.class, value)); return true;
        case "scheduler": target.setScheduler(property(zwangineContext, Object.class, value)); return true;
        case "schedulerproperties":
        case "schedulerProperties": target.setSchedulerProperties(property(zwangineContext, Map.class, value)); return true;
        case "sendemptymessagewhenidle":
        case "sendEmptyMessageWhenIdle": target.setSendEmptyMessageWhenIdle(property(zwangineContext, boolean.class, value)); return true;
        case "shuffle": target.setShuffle(property(zwangineContext, boolean.class, value)); return true;
        case "sortby":
        case "sortBy": target.setSortBy(property(zwangineContext, String.class, value)); return true;
        case "sorter": target.setSorter(property(zwangineContext, java.util.Comparator.class, value)); return true;
        case "startscheduler":
        case "startScheduler": target.setStartScheduler(property(zwangineContext, boolean.class, value)); return true;
        case "startingdirectorymustexist":
        case "startingDirectoryMustExist": target.setStartingDirectoryMustExist(property(zwangineContext, boolean.class, value)); return true;
        case "startingdirectorymusthaveaccess":
        case "startingDirectoryMustHaveAccess": target.setStartingDirectoryMustHaveAccess(property(zwangineContext, boolean.class, value)); return true;
        case "synchronous": target.setSynchronous(property(zwangineContext, boolean.class, value)); return true;
        case "tempfilename":
        case "tempFileName": target.setTempFileName(property(zwangineContext, String.class, value)); return true;
        case "tempprefix":
        case "tempPrefix": target.setTempPrefix(property(zwangineContext, String.class, value)); return true;
        case "timeunit":
        case "timeUnit": target.setTimeUnit(property(zwangineContext, java.util.concurrent.TimeUnit.class, value)); return true;
        case "usefixeddelay":
        case "useFixedDelay": target.setUseFixedDelay(property(zwangineContext, boolean.class, value)); return true;
        default: return false;
        }
    }

    @Override
    public Class<?> getOptionType(String name, boolean ignoreCase) {
        switch (ignoreCase ? name.toLowerCase() : name) {
        case "allownullbody":
        case "allowNullBody": return boolean.class;
        case "antexclude":
        case "antExclude": return String.class;
        case "antfiltercasesensitive":
        case "antFilterCaseSensitive": return boolean.class;
        case "antinclude":
        case "antInclude": return String.class;
        case "appendchars":
        case "appendChars": return String.class;
        case "autocreate":
        case "autoCreate": return boolean.class;
        case "autocreatestepwise":
        case "autoCreateStepwise": return boolean.class;
        case "backofferrorthreshold":
        case "backoffErrorThreshold": return int.class;
        case "backoffidlethreshold":
        case "backoffIdleThreshold": return int.class;
        case "backoffmultiplier":
        case "backoffMultiplier": return int.class;
        case "bridgeerrorhandler":
        case "bridgeErrorHandler": return boolean.class;
        case "browselimit":
        case "browseLimit": return int.class;
        case "buffersize":
        case "bufferSize": return int.class;
        case "charset": return String.class;
        case "checksumfilealgorithm":
        case "checksumFileAlgorithm": return String.class;
        case "chmod": return String.class;
        case "chmoddirectory":
        case "chmodDirectory": return String.class;
        case "copyanddeleteonrenamefail":
        case "copyAndDeleteOnRenameFail": return boolean.class;
        case "delay": return long.class;
        case "delete": return boolean.class;
        case "directorymustexist":
        case "directoryMustExist": return boolean.class;
        case "donefilename":
        case "doneFileName": return String.class;
        case "eagerdeletetargetfile":
        case "eagerDeleteTargetFile": return boolean.class;
        case "eagermaxmessagesperpoll":
        case "eagerMaxMessagesPerPoll": return boolean.class;
        case "exceptionhandler":
        case "exceptionHandler": return org.zenithblox.spi.ExceptionHandler.class;
        case "exchangepattern":
        case "exchangePattern": return org.zenithblox.ExchangePattern.class;
        case "exclude": return String.class;
        case "excludeext":
        case "excludeExt": return String.class;
        case "exclusivereadlockstrategy":
        case "exclusiveReadLockStrategy": return org.zenithblox.component.file.GenericFileExclusiveReadLockStrategy.class;
        case "extendedattributes":
        case "extendedAttributes": return String.class;
        case "fileexist":
        case "fileExist": return org.zenithblox.component.file.GenericFileExist.class;
        case "filename":
        case "fileName": return String.class;
        case "filter": return org.zenithblox.component.file.GenericFileFilter.class;
        case "filterdirectory":
        case "filterDirectory": return String.class;
        case "filterfile":
        case "filterFile": return String.class;
        case "flatten": return boolean.class;
        case "forcewrites":
        case "forceWrites": return boolean.class;
        case "greedy": return boolean.class;
        case "idempotent": return Boolean.class;
        case "idempotenteager":
        case "idempotentEager": return Boolean.class;
        case "idempotentkey":
        case "idempotentKey": return String.class;
        case "idempotentrepository":
        case "idempotentRepository": return org.zenithblox.spi.IdempotentRepository.class;
        case "inprogressrepository":
        case "inProgressRepository": return org.zenithblox.spi.IdempotentRepository.class;
        case "include": return String.class;
        case "includeext":
        case "includeExt": return String.class;
        case "includehiddendirs":
        case "includeHiddenDirs": return boolean.class;
        case "includehiddenfiles":
        case "includeHiddenFiles": return boolean.class;
        case "initialdelay":
        case "initialDelay": return long.class;
        case "jailstartingdirectory":
        case "jailStartingDirectory": return boolean.class;
        case "keeplastmodified":
        case "keepLastModified": return boolean.class;
        case "lazystartproducer":
        case "lazyStartProducer": return boolean.class;
        case "localworkdirectory":
        case "localWorkDirectory": return String.class;
        case "maxdepth":
        case "maxDepth": return int.class;
        case "maxmessagesperpoll":
        case "maxMessagesPerPoll": return int.class;
        case "mindepth":
        case "minDepth": return int.class;
        case "move": return String.class;
        case "moveexisting":
        case "moveExisting": return String.class;
        case "moveexistingfilestrategy":
        case "moveExistingFileStrategy": return org.zenithblox.component.file.strategy.FileMoveExistingStrategy.class;
        case "movefailed":
        case "moveFailed": return String.class;
        case "noop": return boolean.class;
        case "oncompletionexceptionhandler":
        case "onCompletionExceptionHandler": return org.zenithblox.spi.ExceptionHandler.class;
        case "pollstrategy":
        case "pollStrategy": return org.zenithblox.spi.PollingConsumerPollStrategy.class;
        case "premove":
        case "preMove": return String.class;
        case "presort":
        case "preSort": return boolean.class;
        case "probecontenttype":
        case "probeContentType": return boolean.class;
        case "processstrategy":
        case "processStrategy": return org.zenithblox.component.file.GenericFileProcessStrategy.class;
        case "readlock":
        case "readLock": return String.class;
        case "readlockcheckinterval":
        case "readLockCheckInterval": return long.class;
        case "readlockdeleteorphanlockfiles":
        case "readLockDeleteOrphanLockFiles": return boolean.class;
        case "readlockidempotentreleaseasync":
        case "readLockIdempotentReleaseAsync": return boolean.class;
        case "readlockidempotentreleaseasyncpoolsize":
        case "readLockIdempotentReleaseAsyncPoolSize": return int.class;
        case "readlockidempotentreleasedelay":
        case "readLockIdempotentReleaseDelay": return int.class;
        case "readlockidempotentreleaseexecutorservice":
        case "readLockIdempotentReleaseExecutorService": return java.util.concurrent.ScheduledExecutorService.class;
        case "readlocklogginglevel":
        case "readLockLoggingLevel": return org.zenithblox.LoggingLevel.class;
        case "readlockmarkerfile":
        case "readLockMarkerFile": return boolean.class;
        case "readlockminage":
        case "readLockMinAge": return long.class;
        case "readlockminlength":
        case "readLockMinLength": return long.class;
        case "readlockremoveoncommit":
        case "readLockRemoveOnCommit": return boolean.class;
        case "readlockremoveonrollback":
        case "readLockRemoveOnRollback": return boolean.class;
        case "readlocktimeout":
        case "readLockTimeout": return long.class;
        case "recursive": return boolean.class;
        case "renameusingcopy":
        case "renameUsingCopy": return boolean.class;
        case "repeatcount":
        case "repeatCount": return long.class;
        case "runlogginglevel":
        case "runLoggingLevel": return org.zenithblox.LoggingLevel.class;
        case "scheduledexecutorservice":
        case "scheduledExecutorService": return java.util.concurrent.ScheduledExecutorService.class;
        case "scheduler": return Object.class;
        case "schedulerproperties":
        case "schedulerProperties": return Map.class;
        case "sendemptymessagewhenidle":
        case "sendEmptyMessageWhenIdle": return boolean.class;
        case "shuffle": return boolean.class;
        case "sortby":
        case "sortBy": return String.class;
        case "sorter": return java.util.Comparator.class;
        case "startscheduler":
        case "startScheduler": return boolean.class;
        case "startingdirectorymustexist":
        case "startingDirectoryMustExist": return boolean.class;
        case "startingdirectorymusthaveaccess":
        case "startingDirectoryMustHaveAccess": return boolean.class;
        case "synchronous": return boolean.class;
        case "tempfilename":
        case "tempFileName": return String.class;
        case "tempprefix":
        case "tempPrefix": return String.class;
        case "timeunit":
        case "timeUnit": return java.util.concurrent.TimeUnit.class;
        case "usefixeddelay":
        case "useFixedDelay": return boolean.class;
        default: return null;
        }
    }

    @Override
    public Object getOptionValue(Object obj, String name, boolean ignoreCase) {
        FileEndpoint target = (FileEndpoint) obj;
        switch (ignoreCase ? name.toLowerCase() : name) {
        case "allownullbody":
        case "allowNullBody": return target.isAllowNullBody();
        case "antexclude":
        case "antExclude": return target.getAntExclude();
        case "antfiltercasesensitive":
        case "antFilterCaseSensitive": return target.isAntFilterCaseSensitive();
        case "antinclude":
        case "antInclude": return target.getAntInclude();
        case "appendchars":
        case "appendChars": return target.getAppendChars();
        case "autocreate":
        case "autoCreate": return target.isAutoCreate();
        case "autocreatestepwise":
        case "autoCreateStepwise": return target.isAutoCreateStepwise();
        case "backofferrorthreshold":
        case "backoffErrorThreshold": return target.getBackoffErrorThreshold();
        case "backoffidlethreshold":
        case "backoffIdleThreshold": return target.getBackoffIdleThreshold();
        case "backoffmultiplier":
        case "backoffMultiplier": return target.getBackoffMultiplier();
        case "bridgeerrorhandler":
        case "bridgeErrorHandler": return target.isBridgeErrorHandler();
        case "browselimit":
        case "browseLimit": return target.getBrowseLimit();
        case "buffersize":
        case "bufferSize": return target.getBufferSize();
        case "charset": return target.getCharset();
        case "checksumfilealgorithm":
        case "checksumFileAlgorithm": return target.getChecksumFileAlgorithm();
        case "chmod": return target.getChmod();
        case "chmoddirectory":
        case "chmodDirectory": return target.getChmodDirectory();
        case "copyanddeleteonrenamefail":
        case "copyAndDeleteOnRenameFail": return target.isCopyAndDeleteOnRenameFail();
        case "delay": return target.getDelay();
        case "delete": return target.isDelete();
        case "directorymustexist":
        case "directoryMustExist": return target.isDirectoryMustExist();
        case "donefilename":
        case "doneFileName": return target.getDoneFileName();
        case "eagerdeletetargetfile":
        case "eagerDeleteTargetFile": return target.isEagerDeleteTargetFile();
        case "eagermaxmessagesperpoll":
        case "eagerMaxMessagesPerPoll": return target.isEagerMaxMessagesPerPoll();
        case "exceptionhandler":
        case "exceptionHandler": return target.getExceptionHandler();
        case "exchangepattern":
        case "exchangePattern": return target.getExchangePattern();
        case "exclude": return target.getExclude();
        case "excludeext":
        case "excludeExt": return target.getExcludeExt();
        case "exclusivereadlockstrategy":
        case "exclusiveReadLockStrategy": return target.getExclusiveReadLockStrategy();
        case "extendedattributes":
        case "extendedAttributes": return target.getExtendedAttributes();
        case "fileexist":
        case "fileExist": return target.getFileExist();
        case "filename":
        case "fileName": return target.getFileName();
        case "filter": return target.getFilter();
        case "filterdirectory":
        case "filterDirectory": return target.getFilterDirectory();
        case "filterfile":
        case "filterFile": return target.getFilterFile();
        case "flatten": return target.isFlatten();
        case "forcewrites":
        case "forceWrites": return target.isForceWrites();
        case "greedy": return target.isGreedy();
        case "idempotent": return target.getIdempotent();
        case "idempotenteager":
        case "idempotentEager": return target.getIdempotentEager();
        case "idempotentkey":
        case "idempotentKey": return target.getIdempotentKey();
        case "idempotentrepository":
        case "idempotentRepository": return target.getIdempotentRepository();
        case "inprogressrepository":
        case "inProgressRepository": return target.getInProgressRepository();
        case "include": return target.getInclude();
        case "includeext":
        case "includeExt": return target.getIncludeExt();
        case "includehiddendirs":
        case "includeHiddenDirs": return target.isIncludeHiddenDirs();
        case "includehiddenfiles":
        case "includeHiddenFiles": return target.isIncludeHiddenFiles();
        case "initialdelay":
        case "initialDelay": return target.getInitialDelay();
        case "jailstartingdirectory":
        case "jailStartingDirectory": return target.isJailStartingDirectory();
        case "keeplastmodified":
        case "keepLastModified": return target.isKeepLastModified();
        case "lazystartproducer":
        case "lazyStartProducer": return target.isLazyStartProducer();
        case "localworkdirectory":
        case "localWorkDirectory": return target.getLocalWorkDirectory();
        case "maxdepth":
        case "maxDepth": return target.getMaxDepth();
        case "maxmessagesperpoll":
        case "maxMessagesPerPoll": return target.getMaxMessagesPerPoll();
        case "mindepth":
        case "minDepth": return target.getMinDepth();
        case "move": return target.getMove();
        case "moveexisting":
        case "moveExisting": return target.getMoveExisting();
        case "moveexistingfilestrategy":
        case "moveExistingFileStrategy": return target.getMoveExistingFileStrategy();
        case "movefailed":
        case "moveFailed": return target.getMoveFailed();
        case "noop": return target.isNoop();
        case "oncompletionexceptionhandler":
        case "onCompletionExceptionHandler": return target.getOnCompletionExceptionHandler();
        case "pollstrategy":
        case "pollStrategy": return target.getPollStrategy();
        case "premove":
        case "preMove": return target.getPreMove();
        case "presort":
        case "preSort": return target.isPreSort();
        case "probecontenttype":
        case "probeContentType": return target.isProbeContentType();
        case "processstrategy":
        case "processStrategy": return target.getProcessStrategy();
        case "readlock":
        case "readLock": return target.getReadLock();
        case "readlockcheckinterval":
        case "readLockCheckInterval": return target.getReadLockCheckInterval();
        case "readlockdeleteorphanlockfiles":
        case "readLockDeleteOrphanLockFiles": return target.isReadLockDeleteOrphanLockFiles();
        case "readlockidempotentreleaseasync":
        case "readLockIdempotentReleaseAsync": return target.isReadLockIdempotentReleaseAsync();
        case "readlockidempotentreleaseasyncpoolsize":
        case "readLockIdempotentReleaseAsyncPoolSize": return target.getReadLockIdempotentReleaseAsyncPoolSize();
        case "readlockidempotentreleasedelay":
        case "readLockIdempotentReleaseDelay": return target.getReadLockIdempotentReleaseDelay();
        case "readlockidempotentreleaseexecutorservice":
        case "readLockIdempotentReleaseExecutorService": return target.getReadLockIdempotentReleaseExecutorService();
        case "readlocklogginglevel":
        case "readLockLoggingLevel": return target.getReadLockLoggingLevel();
        case "readlockmarkerfile":
        case "readLockMarkerFile": return target.isReadLockMarkerFile();
        case "readlockminage":
        case "readLockMinAge": return target.getReadLockMinAge();
        case "readlockminlength":
        case "readLockMinLength": return target.getReadLockMinLength();
        case "readlockremoveoncommit":
        case "readLockRemoveOnCommit": return target.isReadLockRemoveOnCommit();
        case "readlockremoveonrollback":
        case "readLockRemoveOnRollback": return target.isReadLockRemoveOnRollback();
        case "readlocktimeout":
        case "readLockTimeout": return target.getReadLockTimeout();
        case "recursive": return target.isRecursive();
        case "renameusingcopy":
        case "renameUsingCopy": return target.isRenameUsingCopy();
        case "repeatcount":
        case "repeatCount": return target.getRepeatCount();
        case "runlogginglevel":
        case "runLoggingLevel": return target.getRunLoggingLevel();
        case "scheduledexecutorservice":
        case "scheduledExecutorService": return target.getScheduledExecutorService();
        case "scheduler": return target.getScheduler();
        case "schedulerproperties":
        case "schedulerProperties": return target.getSchedulerProperties();
        case "sendemptymessagewhenidle":
        case "sendEmptyMessageWhenIdle": return target.isSendEmptyMessageWhenIdle();
        case "shuffle": return target.isShuffle();
        case "sortby":
        case "sortBy": return target.getSortBy();
        case "sorter": return target.getSorter();
        case "startscheduler":
        case "startScheduler": return target.isStartScheduler();
        case "startingdirectorymustexist":
        case "startingDirectoryMustExist": return target.isStartingDirectoryMustExist();
        case "startingdirectorymusthaveaccess":
        case "startingDirectoryMustHaveAccess": return target.isStartingDirectoryMustHaveAccess();
        case "synchronous": return target.isSynchronous();
        case "tempfilename":
        case "tempFileName": return target.getTempFileName();
        case "tempprefix":
        case "tempPrefix": return target.getTempPrefix();
        case "timeunit":
        case "timeUnit": return target.getTimeUnit();
        case "usefixeddelay":
        case "useFixedDelay": return target.isUseFixedDelay();
        default: return null;
        }
    }

    @Override
    public Object getCollectionValueType(Object target, String name, boolean ignoreCase) {
        switch (ignoreCase ? name.toLowerCase() : name) {
        case "exclusivereadlockstrategy":
        case "exclusiveReadLockStrategy": return java.io.File.class;
        case "filter": return java.io.File.class;
        case "processstrategy":
        case "processStrategy": return java.io.File.class;
        case "schedulerproperties":
        case "schedulerProperties": return Object.class;
        case "sorter": return org.zenithblox.component.file.GenericFile.class;
        default: return null;
        }
    }
}

