/* Generated by zwangine build tools - do NOT edit this file! */
package org.zenithblox.component.file;

import org.zenithblox.ZwangineContext;
import org.zenithblox.ZwangineContextAware;
import org.zenithblox.DeferredContextBinding;
import org.zenithblox.TypeConverterLoaderException;
import org.zenithblox.spi.TypeConverterLoader;
import org.zenithblox.spi.TypeConverterRegistry;
import org.zenithblox.support.SimpleTypeConverter;

import javax.annotation.processing.Generated;

/**
 * Generated by zwangine build tools - do NOT edit this file!
 */
@Generated("org.zenithblox.maven.packaging.TypeConverterLoaderGeneratorMojo")
@SuppressWarnings("unchecked")
@DeferredContextBinding
public final class GenericFileConverterLoader implements TypeConverterLoader, ZwangineContextAware {

    private ZwangineContext zwangineContext;

    public GenericFileConverterLoader() {
    }

    @Override
    public void setZwangineContext(ZwangineContext zwangineContext) {
        this.zwangineContext = zwangineContext;
    }

    @Override
    public ZwangineContext getZwangineContext() {
        return zwangineContext;
    }

    @Override
    public void load(TypeConverterRegistry registry) throws TypeConverterLoaderException {
        registerConverters(registry);
        registerFallbackConverters(registry);
    }

    private void registerConverters(TypeConverterRegistry registry) {
        addTypeConverter(registry, java.io.InputStream.class, org.zenithblox.component.file.GenericFile.class, false,
            (type, exchange, value) -> org.zenithblox.component.file.GenericFileConverter.genericFileToInputStream((org.zenithblox.component.file.GenericFile) value, exchange));
        addTypeConverter(registry, java.io.Reader.class, org.zenithblox.component.file.GenericFile.class, false,
            (type, exchange, value) -> org.zenithblox.component.file.GenericFileConverter.genericFileToReader((org.zenithblox.component.file.GenericFile) value, exchange));
        addTypeConverter(registry, java.io.Serializable.class, org.zenithblox.component.file.GenericFile.class, false,
            (type, exchange, value) -> org.zenithblox.component.file.GenericFileConverter.genericFileToSerializable((org.zenithblox.component.file.GenericFile) value, exchange));
        addTypeConverter(registry, String.class, org.zenithblox.component.file.GenericFile.class, false,
            (type, exchange, value) -> org.zenithblox.component.file.GenericFileConverter.genericFileToString((org.zenithblox.component.file.GenericFile) value, exchange));
    }

    private static void addTypeConverter(TypeConverterRegistry registry, Class<?> toType, Class<?> fromType, boolean allowNull, SimpleTypeConverter.ConversionMethod method) {
        registry.addTypeConverter(toType, fromType, new SimpleTypeConverter(allowNull, method));
    }

    private void registerFallbackConverters(TypeConverterRegistry registry) {
        addFallbackTypeConverter(registry, false, false, (type, exchange, value) -> org.zenithblox.component.file.GenericFileConverter.convertTo(type, exchange, value, registry));
    }

    private static void addFallbackTypeConverter(TypeConverterRegistry registry, boolean allowNull, boolean canPromote, SimpleTypeConverter.ConversionMethod method) {
        registry.addFallbackTypeConverter(new SimpleTypeConverter(allowNull, method), canPromote);
    }
}
